### ISSUE TITLE
Provide color palette for Open-Source contribution

### ISSUE THREAD

**Issue by evertonandrade** [enkia/tokyo-night-vscode-theme#26] opened 2021-03-23 00:19 UTC
Hello, could you provide guidance for the color palette so that contributors can easily port this theme to other applications or platforms. It could become something similar to Dracula's project. You can check it out at [Dracula](https://draculatheme.com) for inspiration. Thanks!

**Comment by enkia** [comment] 2021-03-24 02:20
This is a dupe of the other issue so I'll close this after commenting. Feel free to respond in the other issue, though. 

I was hoping to have it finished by the end of the holidays and obviously that didn't happen, but I'm about half way done.  Basically, I still have all of the light theme colors to do and finalizing / proof reading the dark. I've been using [Noctis's markdown table](https://github.com/liviuschera/noctis/blob/master/README.md) as a template. What I have done so far for Tokyo Night/Storm may help you while I finish up the rest? 

| Color      | Hex                                                          | Use                                           |
| ---------- | ------------------------------------------------------------ | --------------------------------------------- |
| Red          | ![#f7768e](https://placehold.it/15/f7768e/000000?text=+) `#f7768e` | This keyword, HTML elements, Regex group symbol, Number constants, Terminal Red |
| Orange       | ![#ff9e64](https://placehold.it/15/ff9e64/000000?text=+) `#ff9e64` | Function parameters, Language support constants, Regex character sets |
| Yellow       | ![#e0af68](https://placehold.it/15/e0af68/000000?text=+) `#e0af68` | PHP Globals, Terminal Yellow |
| Yellow Green | ![#9ece6a](https://placehold.it/15/9ece6a/000000?text=+) `#9ece6a` | Strings, CSS class names |
| Green        | ![#73daca](https://placehold.it/15/73daca/000000?text=+) `#73daca` | Object literal keys, Markdown links, Terminal Green |
| Cyan | ![#b4f9f8](https://placehold.it/15/b4f9f8/000000?text=+) `#b4f9f8` | Regex literals |
| Blue green   | ![#2ac3de](https://placehold.it/15/2ac3de/000000?text=+) `#2ac3de` | Language support functions, CSS HTML elements |
| Light blue | ![#7dcfff](https://placehold.it/15/7dcfff/000000?text=+) `#7dcfff` | Object properties, Regex quantifiers and flags, Terminal Cyan, Markdown code, Import/export keywords |
| Blue         | ![#7aa2f7](https://placehold.it/15/7aa2f7/000000?text=+) `#7aa2f7` | Function names, Terminal Blue |
| Purple       | ![#bb9af7](https://placehold.it/15/bb9af7/000000?text=+) `#bb9af7` | Control Keywords, Storage Types, Regex start/end of string, HTML Attributes, Terminal Magenta |
| White        | ![#c0caf5](https://placehold.it/15/c0caf5/000000?text=+) `#c0caf5` | Variables, Terminal White |
| Light Gray   | ![#9aa5ce](https://placehold.it/15/9aa5ce/000000?text=+) `#9aa5ce` | Foreground |
| Black        | ![#24283b](https://placehold.it/15/24283b/000000?text=+) `#24283b` | Background, Terminal Black |

**Closed by enkia** 2021-03-24 02:20 UTC
